# Generated by Django 4.1 on 2022-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='data',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='data',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
