# Generated by Django 3.1.7 on 2022-08-13 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_csv_file_data_excel_file_data_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='AceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='fileData/')),
                ('file_type', models.CharField(choices=[('EXCEL', 'Excel'), ('CSV', 'CSV (Comma Separated Values)'), ('PDF', 'PDF'), ('OTHER', 'other')], default='OTHER', max_length=10)),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.acedata')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
