# Generated by Django 3.1.7 on 2022-08-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20220813_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='acefile',
            name='file_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acefile',
            name='file_type',
            field=models.CharField(choices=[('EXCEL', 'Excel'), ('CSV', 'CSV (Comma Separated Values)'), ('PDF', 'PDF'), ('OTHER', 'other')], default='', max_length=10, null=True),
        ),
    ]
