# Generated by Django 4.1 on 2022-08-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_auto_20220813_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="banner_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
