# Generated by Django 4.1 on 2022-08-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_indicator_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedata',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='fileData/'),
        ),
    ]
