# Generated by Django 4.1 on 2022-08-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_acedata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedata',
            name='data_numbers',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='acedata',
            name='years_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
