# Generated by Django 4.1 on 2022-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_acedata_data_numbers_acedata_years_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedata',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
