# Generated by Django 4.1 on 2022-09-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_acedata_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='banner_img',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
    ]
