# Generated by Django 4.1 on 2022-09-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_acedata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedata',
            name='data_excel',
            field=models.FileField(blank=True, null=True, upload_to='fileData/'),
        ),
    ]
