# Generated by Django 4.2.1 on 2023-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_acedata_data_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
