# Generated by Django 4.2.1 on 2024-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_category_post_subcategory_delete_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(max_length=15)),
            ],
        ),
    ]
