# Generated by Django 5.0.1 on 2024-01-31 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_country_year_delete_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryoverview',
            name='Year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.year'),
        ),
    ]
