# Generated by Django 5.0.1 on 2024-01-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_country_iso_code_remove_country_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Region',
        ),
    ]
