# Generated by Django 5.0.1 on 2024-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_rename_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
