"""
Django settings for acedata project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!js&#cufq%u3m$$me=7!%vo0sc50!4(_d-nms562g*11%x_8e#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.data.aceadvisors.org', 'data.aceadvisors.org','127.0.0.1']

BASE_URL = 'http://127.0.0.1:8000'
# Application definition

INSTALLED_APPS = [
    #'DATA.ACEADVISORS.ORG',
    'data.apps.DataConfig',
    'regulatory_overview.apps.RegulatoryOverviewConfig',
    #'Investment_Lifecycle.InvestmentLifecycleConfig'
    'django.contrib.admin',
    'django.contrib.auth', # start project lay by default created, both authentication authorization
    'django.contrib.contenttypes', # allow permission to associate with models we create
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'Investment_Lifecycle',
    #'smart_selects',
    #'django_filters',
    'rest_framework',
    'corsheaders', 
    'django_countries',


    #'data.aceadvisors.org'


   
    
]
SESSION_COOKIE_AGE = 3600


MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # manage session across request
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', #Adds protection against Cross Site Request Forgeries(forgid) by adding hidden form fields to POST forms and checking requests for the correct value
    'django.contrib.auth.middleware.AuthenticationMiddleware', # associate users with request using sessions
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


    'django.middleware.csrf.CsrfViewMiddleware',
    #'data.admin_session_timeout.AdminSessionTimeoutMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',

    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'acedata.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'data.context_processor.get_indicators'
            ],
        },
    },
]

WSGI_APPLICATION = 'acedata.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    #'default': {  
        #'ENGINE': 'django.db.backends.mysql',  
        #'NAME': 'aceadvisorsorg_platform_db',  
        #'USER': 'aceadvisorsorg_getaw',  
        #'PASSWORD': 'gemhA8xircuksefdyx',  
        #'HOST': 'localhost',  
        #'PORT': '3306',  
        #'OPTIONS': {  
           # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  
        #} 
        # DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'testdb',
        'USER': 'root',
        'PASSWORD': '#Ruth1863',
        'HOST': 'localhost',
        'PORT': '3306',
    }
} 
   
    # 'default': {  
    #     'ENGINE': 'django.db.backends.postgresql',  
    #     'NAME': 'ace',  
    #     'USER': 'nahuapple',  
    #     'PASSWORD': '',  
    #     'HOST': 'localhost',  
    #     'PORT': '5432',  
    # } 



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

LOGIN_URL ='/admin/'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
EMAIL_HOST_USER = None
EMAIL_HOST_PASSWORD = None
EMAIL_USE_TLS = False
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media/')


CORS_ALLOW_ALL_ORIGINS = True