# Generated by Django 4.1 on 2022-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalStrategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='national_strategies/')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Directives', 'Directives'), ('Proclamations', 'Proclamations'), ('Regulations', 'Regulations')], default='', max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='regulatory_framework/')),
            ],
        ),
    ]
