# Generated by Django 4.1 on 2022-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalstrategies',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='national_strategies/'),
        ),
        migrations.AlterField(
            model_name='regulatoryframework',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='regulatory_framework/'),
        ),
    ]
