# Generated by Django 4.2.1 on 2023-07-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0002_alter_nationalstrategies_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('blurred_pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/blurred/')),
            ],
        ),
    ]
