# Generated by Django 4.2.1 on 2023-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0004_testenviroment_delete_uploadedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalstrategies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
