# Generated by Django 4.2.1 on 2023-08-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0005_nationalstrategies_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalstrategies',
            name='description',
        ),
        migrations.AddField(
            model_name='nationalstrategies',
            name='detail_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nationalstrategies',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
