# Generated by Django 4.2.1 on 2023-08-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0006_remove_nationalstrategies_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestEnviroment',
            new_name='TitleWithDetail',
        ),
    ]
