# Generated by Django 4.2.1 on 2023-08-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0007_rename_testenviroment_titlewithdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalstrategies',
            name='file',
        ),
    ]
