# Generated by Django 4.2.1 on 2023-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0008_remove_nationalstrategies_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalstrategies',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='national_strategies/'),
        ),
        migrations.AlterField(
            model_name='titlewithdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='title_with_details/'),
        ),
    ]
