# Generated by Django 4.2.1 on 2023-08-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0009_nationalstrategies_file_alter_titlewithdetail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalstrategies',
            name='detail_paragraph',
        ),
        migrations.RemoveField(
            model_name='nationalstrategies',
            name='name',
        ),
    ]
