# Generated by Django 4.2.1 on 2023-08-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0010_remove_nationalstrategies_detail_paragraph_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalStrategies',
        ),
    ]
