# Generated by Django 4.2.1 on 2023-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0012_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
