# Generated by Django 4.2.1 on 2023-08-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0019_alter_category_name_alter_post_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
