# Generated by Django 4.2.1 on 2023-12-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0026_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
