# Generated by Django 4.2.1 on 2023-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0027_frontslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
