# Generated by Django 4.2.1 on 2023-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0028_frontslider_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frontslider',
        ),
    ]
