# Generated by Django 4.2.1 on 2024-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0029_delete_frontslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='TitleWithDetail',
        ),
        migrations.AlterField(
            model_name='regulatoryframework',
            name='category',
            field=models.CharField(choices=[('Directives', 'Directives'), ('Proclamations', 'Proclamations'), ('Regulations', 'Regulations'), ('Manual', 'Manual')], default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
