# Generated by Django 5.0.1 on 2024-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0034_nationalstrategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalstrategies',
            name='Status',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='', max_length=100, null=True),
        ),
    ]
