# Generated by Django 5.0.1 on 2024-01-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0036_alter_nationalstrategies_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalstrategies',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='regulatory_framework/'),
        ),
        migrations.AlterField(
            model_name='regulatoryframework',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='regulatory_framework/'),
        ),
    ]
