# Generated by Django 5.0.1 on 2024-02-05 18:49

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0044_alter_nationalstrategies_endyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=django_countries.fields.CountryField(default='Ethiopia', max_length=2),
        ),
    ]
