# Generated by Django 5.0.1 on 2024-02-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0045_alter_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
