# Generated by Django 5.0.1 on 2024-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0047_nationalstrategies_pdftitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryframework',
            name='pdfTitle',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
