# Generated by Django 5.0.1 on 2024-02-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0048_regulatoryframework_pdftitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationalstrategies',
            old_name='pdfTitle',
            new_name='Title',
        ),
    ]
