# Generated by Django 5.0 on 2024-02-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0051_startyear_rename_year_endyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryframework',
            name='EYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulatory_overview.endyear'),
        ),
        migrations.AddField(
            model_name='regulatoryframework',
            name='SYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulatory_overview.startyear'),
        ),
    ]
