# Generated by Django 5.0 on 2024-02-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0053_year_remove_regulatoryframework_syear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationalstrategies',
            old_name='Title',
            new_name='PdfTitle',
        ),
        migrations.RenameField(
            model_name='regulatoryframework',
            old_name='pdfTitle',
            new_name='PdfTitle',
        ),
    ]
