# Generated by Django 5.0 on 2024-02-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_overview', '0054_rename_title_nationalstrategies_pdftitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegulatoryFramework',
            new_name='BusinessStrategy',
        ),
    ]
